// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           14
// Async Callback (empty):               1
// Total number of exported functions:  16

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    id_verifier
    (
        init => init
        register => register
        deleteAccount => delete_account
        submitAttestation => submit_attestation
        logout => logout
        getAccountBySerial => get_account_by_serial
        getPublicKeyBySerial => get_public_key_by_serial
        getNameBySerial => get_name_by_serial
        isRegisteredBySerial => is_registered_by_serial
        getLoginStatusBySerial => get_login_status_by_serial
        getWalletBySerial => get_wallet_by_serial
        getTrustedVerifier => get_trusted_verifier
        isWalletLinked => is_wallet_linked
        getSerialByWallet => get_serial_by_wallet
        getLoginNonce => get_login_nonce_view
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
